//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsumeWcfCrud.WcfCrudRef {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EmpDetails", Namespace="http://schemas.datacontract.org/2004/07/Wcf_Crud")]
    [System.SerializableAttribute()]
    public partial class EmpDetails : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DeptIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DeptNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SalaryField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DeptId {
            get {
                return this.DeptIdField;
            }
            set {
                if ((object.ReferenceEquals(this.DeptIdField, value) != true)) {
                    this.DeptIdField = value;
                    this.RaisePropertyChanged("DeptId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DeptName {
            get {
                return this.DeptNameField;
            }
            set {
                if ((object.ReferenceEquals(this.DeptNameField, value) != true)) {
                    this.DeptNameField = value;
                    this.RaisePropertyChanged("DeptName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Salary {
            get {
                return this.SalaryField;
            }
            set {
                if ((object.ReferenceEquals(this.SalaryField, value) != true)) {
                    this.SalaryField = value;
                    this.RaisePropertyChanged("Salary");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WcfCrudRef.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/InsertEmpDetails", ReplyAction="http://tempuri.org/IService1/InsertEmpDetailsResponse")]
        string InsertEmpDetails(ConsumeWcfCrud.WcfCrudRef.EmpDetails eDatils);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/InsertEmpDetails", ReplyAction="http://tempuri.org/IService1/InsertEmpDetailsResponse")]
        System.Threading.Tasks.Task<string> InsertEmpDetailsAsync(ConsumeWcfCrud.WcfCrudRef.EmpDetails eDatils);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetEmpDetails", ReplyAction="http://tempuri.org/IService1/GetEmpDetailsResponse")]
        System.Data.DataSet GetEmpDetails(ConsumeWcfCrud.WcfCrudRef.EmpDetails eDatils);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetEmpDetails", ReplyAction="http://tempuri.org/IService1/GetEmpDetailsResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetEmpDetailsAsync(ConsumeWcfCrud.WcfCrudRef.EmpDetails eDatils);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/FetchUpdatedRecords", ReplyAction="http://tempuri.org/IService1/FetchUpdatedRecordsResponse")]
        System.Data.DataSet FetchUpdatedRecords(ConsumeWcfCrud.WcfCrudRef.EmpDetails eDatils);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/FetchUpdatedRecords", ReplyAction="http://tempuri.org/IService1/FetchUpdatedRecordsResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> FetchUpdatedRecordsAsync(ConsumeWcfCrud.WcfCrudRef.EmpDetails eDatils);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateEmpDetails", ReplyAction="http://tempuri.org/IService1/UpdateEmpDetailsResponse")]
        string UpdateEmpDetails(ConsumeWcfCrud.WcfCrudRef.EmpDetails eDatils);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateEmpDetails", ReplyAction="http://tempuri.org/IService1/UpdateEmpDetailsResponse")]
        System.Threading.Tasks.Task<string> UpdateEmpDetailsAsync(ConsumeWcfCrud.WcfCrudRef.EmpDetails eDatils);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteEmpDetails", ReplyAction="http://tempuri.org/IService1/DeleteEmpDetailsResponse")]
        bool DeleteEmpDetails(ConsumeWcfCrud.WcfCrudRef.EmpDetails eDatils);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteEmpDetails", ReplyAction="http://tempuri.org/IService1/DeleteEmpDetailsResponse")]
        System.Threading.Tasks.Task<bool> DeleteEmpDetailsAsync(ConsumeWcfCrud.WcfCrudRef.EmpDetails eDatils);
       
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : ConsumeWcfCrud.WcfCrudRef.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<ConsumeWcfCrud.WcfCrudRef.IService1> {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string InsertEmpDetails(ConsumeWcfCrud.WcfCrudRef.EmpDetails eDatils) {
            return base.Channel.InsertEmpDetails(eDatils);
        }
        
        public System.Threading.Tasks.Task<string> InsertEmpDetailsAsync(ConsumeWcfCrud.WcfCrudRef.EmpDetails eDatils) {
            return base.Channel.InsertEmpDetailsAsync(eDatils);
        }
        
        public System.Data.DataSet GetEmpDetails(ConsumeWcfCrud.WcfCrudRef.EmpDetails eDatils) {
            return base.Channel.GetEmpDetails(eDatils);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetEmpDetailsAsync(ConsumeWcfCrud.WcfCrudRef.EmpDetails eDatils) {
            return base.Channel.GetEmpDetailsAsync(eDatils);
        }
        
        public System.Data.DataSet FetchUpdatedRecords(ConsumeWcfCrud.WcfCrudRef.EmpDetails eDatils) {
            return base.Channel.FetchUpdatedRecords(eDatils);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> FetchUpdatedRecordsAsync(ConsumeWcfCrud.WcfCrudRef.EmpDetails eDatils) {
            return base.Channel.FetchUpdatedRecordsAsync(eDatils);
        }
        
        public string UpdateEmpDetails(ConsumeWcfCrud.WcfCrudRef.EmpDetails eDatils) {
            return base.Channel.UpdateEmpDetails(eDatils);
        }
        
        public System.Threading.Tasks.Task<string> UpdateEmpDetailsAsync(ConsumeWcfCrud.WcfCrudRef.EmpDetails eDatils) {
            return base.Channel.UpdateEmpDetailsAsync(eDatils);
        }
        
        public bool DeleteEmpDetails(ConsumeWcfCrud.WcfCrudRef.EmpDetails eDatils) {
            return base.Channel.DeleteEmpDetails(eDatils);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteEmpDetailsAsync(ConsumeWcfCrud.WcfCrudRef.EmpDetails eDatils) {
            return base.Channel.DeleteEmpDetailsAsync(eDatils);
        }

      

       
    }
}
